name: Desarrollo

# Definimos los servicios que se ejecutarán en los contenedores Docker.
services:
  java:
    image: buenaspracticas:0.0.1-SNAPSHOT
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/desarrollo
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: password123