name: Produccion

# Definimos los servicios que se ejecutarán en los contenedores Docker.
services:
  java:
    image: demo:0.0.1-SNAPSHOT
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/produccion
      SPRING_DATASOURCE_USERNAME: produser
      SPRING_DATASOURCE_PASSWORD: prodpassword
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'produccion'
      MYSQL_USER: 'produser'
      MYSQL_PASSWORD: 'prodpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3303:3306"
    expose:
      - "3303"
    restart: always


