name: ${COMPOSE_NAME}

# Definimos los servicios que se ejecutarán en los contenedores Docker.
services:
  java:
    image: ${PROJECT_NAME}:${VERSION:-snapshot}
    ports:
      - "${PUERTO_DESARROLLO:-8080}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/desarrollodb
      SPRING_DATASOURCE_USERNAME: desarrollouser
      SPRING_DATASOURCE_PASSWORD: desarrollopassword
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
    test: ["CMD-SHELL", "wget -qO- http://localhost:4000/health/liveliness | grep -q \"I'm alive!\""]
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 30s
    restart: always
    expose: 
      - 8080

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'desarrollodb'
      POSTGRES_USER: 'desarrollouser'
      POSTGRES_PASSWORD: 'desarrollopassword'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U desarrollouser -d desarrollodb" ]
      timeout: 20s
      retries: 10
    restart: always
    ports:
      - "${PUERTO_DB_DESARROLLO}:5432"
