name: Subida a Desarrollo

on:
  push:
    branches: [ "desarrollo" ]

jobs:

  # --------------------- COMPILAR, TESTEAR Y CREAR IMAGEN ---------------------
  preparar-entorno:
    runs-on: self-hosted
    env:
      VERSION: snapshot
    steps:
      # Eliminar el directorio si ya existe (evita el error de "destination path already exists")
      - name: Eliminar directorio si existe
        run: |
          if (Test-Path -Path "BuenasPracticasSpringBoot") {
            Remove-Item -Recurse -Force "BuenasPracticasSpringBoot"
          }
      - name: Descargar solo el código necesario
        run: git clone --depth 1 https://github.com/ateixeiramunoz/BuenasPracticasSpringBoot.git

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

  test-unitarios:
    needs: preparar-entorno
    runs-on: self-hosted
    env:
      VERSION: snapshot
    steps:
      # Persistir el cache de Maven en el directorio local
      - name: Compilar y ejecutar tests
        run: mvn -T32 --batch-mode test "-Dmaven.repo.local=C:\Users\maila\.m2\repository"

  test-integracion:
    needs: preparar-entorno
    runs-on: self-hosted
    env:
      VERSION: snapshot
    steps:
      # Persistir el cache de Maven en el directorio local
      - name: Compilar y ejecutar tests
        run: mvn -T32 --batch-mode verify "-Dmaven.repo.local=C:\Users\maila\.m2\repository"
        
  construir_imagen:
    needs: [test-unitarios,test-integracion]
    runs-on: self-hosted
    env:
      VERSION: snapshot
    steps:
      # Construir imagen Docker con cache local
      - name: Construir imagen Docker con builder ligero
        run: mvn -T32 spring-boot:build-image -DskipTests "-Dmaven.repo.local=C:\Users\maila\.m2\repository"


  # --------------------- DESPLEGAR EN SERVIDOR DE DESARROLLO ---------------------
  arrancar_en_servidor_de_desarrollo:
    needs: construir_imagen
    runs-on: self-hosted
    steps:
      # Descargar el código (por si es necesario para el docker-compose)
      - uses: actions/checkout@v4

      # Desplegar con docker compose (usa el nombre del proyecto y los puertos desde secretos)
      - name: Desplegar contenedor de desarrollo
        env:
          COMPOSE_PROJECT_NAME: buenaspracticas-dev
          PUERTO_DESARROLLO: ${{ secrets.PUERTO_DESARROLLO }}
          PUERTO_DB_DESARROLLO: ${{ secrets.PUERTO_DB_DESARROLLO }}
        run: docker compose -f compose-desarrollo.yaml up -d
