name: Subida a Producción (Sin Package)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # --------------------- PREPARAR ENTORNO ---------------------
  preparar_entorno:
    concurrency:
      group: produccion
      cancel-in-progress: true
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17 (Solo si es necesario)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          check-latest: false
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Verificar si `mvn clean` es necesario
        run: |
          if git diff --name-only HEAD^ | grep 'pom.xml'; then
            echo "Cambios detectados en pom.xml, ejecutando mvn clean..."
            mvn -q --batch-mode clean
          else
            echo "No hay cambios en pom.xml, saltando mvn clean."
          fi

      - name: Usar repositorio Maven temporal
        run: mvn -q --batch-mode -Dmaven.repo.local=/tmp/maven-repo dependency:go-offline

  # --------------------- COMPILAR CÓDIGO ---------------------
  compilar_codigo:
    needs: preparar_entorno
    runs-on: self-hosted
    steps:
      - name: Compilar código
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
        run: mvn -q --batch-mode -T16 compile

  # --------------------- TESTS  ---------------------
  ejecutar_tests:
    needs: compilar_codigo
    runs-on: self-hosted
    steps:
      - name: Ejecutar todas las pruebas en paralelo con 16 hilos
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
        run: mvn -q --batch-mode -T16 verify jacoco:report




  # --------------------- ANÁLISIS CON SONARQUBE ---------------------
  analisis_sonarqube:
    needs: [ejecutar_tests]
    runs-on: self-hosted
    steps:
      - name: Ejecutar análisis con SonarQube
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
        run: mvn -q -B -T16 org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar

  # --------------------- CREAR IMAGEN DOCKER (SIN Package) ---------------------
  crear_imagen_docker:
    needs: analisis_sonarqube  # ✅ Ahora depende de SonarQube directamente
    runs-on: self-hosted
    steps:
      - name: Construir imagen Docker con Spring Boot (sin package manual)
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
        run: mvn -q --batch-mode -T16 spring-boot:build-image -DskipTests

  # --------------------- DESPLEGAR EN SERVIDOR ---------------------
  desplegar_en_servidor:
    needs: crear_imagen_docker
    runs-on: self-hosted
    steps:
      - name: Desplegar contenedor en servidor
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
        run: docker compose -f compose-produccion.yaml up -d
