name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  realizar_tests:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Clean
        run: mvn clean
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  package:
    needs: realizar_tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Clean
        run: mvn clean
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots spring-boot:package


  arrancar_en_servidor_de_desarrollo:
    needs: package
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose -f compose-desarrollo.yaml up -d
      
