name: Subida a Producción (Sin Cache Manual)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # --------------------- PREPARAR ENTORNO ---------------------
  preparar_entorno:
    concurrency:
      group: produccion
      cancel-in-progress: true
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          check-latest: false
          cache: maven  # ✅ GitHub Actions manejará el cache automáticamente

  # --------------------- COMPILAR CÓDIGO ---------------------
  compilar_codigo:
    needs: preparar_entorno
    runs-on: self-hosted
    steps:
      - name: Compilar código con `clean verify -Dclean-if-modified`
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
        run: mvn -q --batch-mode -T16 clean verify -Dclean-if-modified -U

  # --------------------- TESTS ---------------------
  ejecutar_tests:
    needs: compilar_codigo
    runs-on: self-hosted
    steps:
      - name: Ejecutar todas las pruebas en paralelo con 16 hilos
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
        run: mvn -q --batch-mode -T16 verify jacoco:report

  # --------------------- ANÁLISIS CON SONARQUBE ---------------------
  analisis_sonarqube:
    needs: [ejecutar_tests]
    runs-on: self-hosted
    steps:
      - name: Ejecutar análisis con SonarQube
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
        run: mvn -q -B -T16 org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar

  # --------------------- CREAR IMAGEN DOCKER ---------------------
  crear_imagen_docker:
    needs: analisis_sonarqube
    runs-on: self-hosted
    steps:
      - name: Construir imagen Docker con Spring Boot
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
        run: mvn -q --batch-mode -T16 spring-boot:build-image -DskipTests

  # --------------------- DESPLEGAR EN SERVIDOR ---------------------
  desplegar_en_servidor:
    needs: crear_imagen_docker
    runs-on: self-hosted
    steps:
      - name: Desplegar contenedor en servidor
        env:
          MAVEN_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=8G"
        run: docker compose -f compose-produccion.yaml up -d
