name: Subida a Desarrollo

on:
  push:
    branches: [ "desarrollo" ]

jobs:

  # --------------------- COMPILAR, TESTEAR Y CREAR IMAGEN ---------------------
  construir_imagen_snapshot:
    runs-on: self-hosted
    env:
      VERSION: snapshot
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ vars.JAVA_VERSION }}'
          distribution: 'temurin'

      - name: Compilar y ejecutar tests
        run: mvn --batch-mode verify

      - name: Construir imagen Docker con tag 'snapshot'
        run: mvn spring-boot:build-image -DskipTests

  # --------------------- DESPLEGAR EN SERVIDOR DE DESARROLLO ---------------------
  arrancar_en_servidor_de_desarrollo:
    needs: construir_imagen_snapshot
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Desplegar contenedor de desarrollo
        env:
          PROJECT_NAME: ${{ vars.CURSO }}-${{ vars.GRUPO }}-dev
          PUERTO_DESARROLLO: ${{ vars.PUERTO_DESARROLLO }}
          PUERTO_DB_DESARROLLO: ${{ vars.PUERTO_DB_DESARROLLO }}
        run: docker compose -f compose-desarrollo.yaml up -d
