name: Subida a Desarrollo

on:
  push:
    branches: [ "desarrollo" ]

jobs:

  # --------------------- CREAR IMAGEN ---------------------
  construir_imagen_snapshot:
    runs-on: self-hosted
    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
    steps:
      - name: Construir imagen con cache de buildpacks
        run: |
          docker volume create pack-cache
          mvn spring-boot:build-image \
            -Dspring-boot.build-image.imageName=${{ vars.PROJECT_NAME }}:${{ env.VERSION }} \
            -Dspring-boot.build-image.environment.PATH=/layers \
            -Dspring-boot.build-image.cache=true

  # --------------------- DESPLEGAR EN SERVIDOR DE DESARROLLO ---------------------
  arrancar_en_servidor_de_desarrollo:
    needs: construir_imagen_snapshot
    runs-on: self-hosted
    steps:
      - name: Desplegar contenedor de desarrollo
        env:
          COMPOSE_NAME: ${{ vars.CURSO }}-${{ vars.GRUPO }}-dev
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          PUERTO_DESARROLLO: ${{ vars.PUERTO_DESARROLLO }}
          PUERTO_DB_DESARROLLO: ${{ vars.PUERTO_DB_DESARROLLO }}
        run: docker compose -f compose-desarrollo.yaml up -d
