name: Subida a Desarrollo

on:
  push:
    branches: [ "desarrollo" ]

jobs:

  # --------------------- CREAR IMAGEN ---------------------
construir_imagen_snapshot:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          # Ruta Windows al repo .m2 del runner
          path: C:\Users\runner\.m2\repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Configurar JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ vars.JAVA_VERSION }}'
          distribution: temurin

      - name: Construir imagen Docker con tag 'snapshot'
        run: mvn spring-boot:build-image -DskipTests

  # --------------------- DESPLEGAR EN SERVIDOR DE DESARROLLO ---------------------
  arrancar_en_servidor_de_desarrollo:
    needs: construir_imagen_snapshot
    runs-on: self-hosted
    steps:
      - name: Desplegar contenedor de desarrollo
        env:
          COMPOSE_NAME: ${{ vars.CURSO }}-${{ vars.GRUPO }}-dev
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          PUERTO_DESARROLLO: ${{ vars.PUERTO_DESARROLLO }}
          PUERTO_DB_DESARROLLO: ${{ vars.PUERTO_DB_DESARROLLO }}
        run: docker compose -f compose-desarrollo.yaml up -d
