name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  realizar_tests:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode verify

  sonarqube:
    runs-on: self-hosted
    steps:
      - name: Build and analyze
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=GoodPractices -Dsonar.projectName='GoodPractices' -Dsonar.host.url=http://localhost:9000 -Dsonar.token=sqp_bad33201cc2abcaaba1449fc2f19b1edded3d6c0

  arrancar_en_servidor_de_desarrollo:
    needs: realizar_tests
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose -f compose-desarrollo.yaml up -d
      
