name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  realizar_tests:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode verify

  sonarqube:
    runs-on: self-hosted
    steps:
      - name: Sonar Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=GoodPractices -Dsonar.projectName=GoodPractices  -Dsonar.token=sqp_361e094157ae95c1fcbca83ae7f7676cd8c0e43c

  arrancar_en_servidor_de_desarrollo:
    needs: realizar_tests
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose -f compose-desarrollo.yaml up -d
      
